---
- name: Pull and push httpd image to ACR
  hosts: vm-cp2
  vars_files:
    - ../vars/acr_vars.yml
  tasks:
    - name: Login to ACR
      containers.podman.podman_login:
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"
        registry: "{{ acr_registry }}"

    - name: Pull images from Docker Hub
      containers.podman.podman_image:
        name: "{{ item.name }}"
        tag: "{{ item.tag }}"
      loop:
        - { name: "docker.io/flaviodev99/httpd_server", tag: "casopractico2" }
        - { name: "docker.io/flaviodev99/ecommerce_api", tag: "cp2" }

    - name: Tag httpd_server image for ACR
      containers.podman.podman_tag:
        image: flaviodev99/httpd_server:casopractico2
        target_names:
          - "{{ acr_registry }}/httpd_server:casopractico2"

    - name: Tag ecommerce_api image for ACR
      containers.podman.podman_tag:
        image: flaviodev99/ecommerce_api:cp2
        target_names:
          - "{{ acr_registry }}/ecommerce_api:casopractico2"

    - name: Push the tagged images to ACR
      containers.podman.podman_image:
        name: "{{ item.name }}"
        push: true
      loop:
        - { name: "{{ acr_registry }}/httpd_server:casopractico2" }
        - { name: "{{ acr_registry }}/ecommerce_api:casopractico2" }

    - name: Remove local image to save space
      containers.podman.podman_image:
        name: "{{ item.name }}"
        state: absent
      loop:
        - { name: "docker.io/httpd_server:casopractico2" }
        - { name: "docker.io/ecommerce_api:cp2" }
      tags: cleanup
