---
- name: Create and manage container to run httpd server with persistence (rootless)
  hosts: vm-cp2
  vars_files:
    - ../vars/acr_vars.yml

  tasks:
    - name: Crea y arranca el contenedor httpd_server
      containers.podman.podman_container:
        name: httpd_server
        image: "{{ acr_registry }}/httpd_server:casopractico2"
        ports:
          - "8443:443"
        state: started
        detach: true
        recreate: true
        restart_policy: always # Mantiene el contenedor activo mientras Podman está corriendo

    - name: Crontab para arrancar el contenedor cuando reinicie la VM
      ansible.builtin.cron:
        name: "Start httpd_server on reboot"
        special_time: reboot
        job: "podman start httpd_server"
        state: present

    - name: Verificar el estado del contenedor
      containers.podman.podman_container_info:
        name: httpd_server
      register: container_info

    - name: Mostrar información del contenedor
      ansible.builtin.debug:
        msg:
          - "El contenedor httpd_server está {{ container_info.containers[0].State.Status }} con ID {{ container_info.containers[0].Id }}"
