---
- name: Create and manage container to run httpd server with persistence (rootless)
  hosts: vm-cp2
  vars_files:
    - ../vars/acr_vars.yml

  tasks:
    - name: Ensure systemd user directory exists
      ansible.builtin.file:
        path: ~/.config/systemd/user
        state: directory
        mode: "0700"

    - name: Create container to run httpd server
      containers.podman.podman_container:
        name: httpd_server
        image: "{{ acr_registry }}/httpd_server:casopractico2"
        ports:
          - "8443:443"
        state: started
        detach: true
        recreate: true
        generate_systemd:
          path: ~/.config/systemd/user/
          restart_policy: always
          names: true

    - name: Reload systemd user daemon
      ansible.builtin.systemd:
        daemon_reload: true
        scope: user
